# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundCode', models.CharField(blank=True, max_length=20, null=True)),
                ('FundName', models.CharField(blank=True, max_length=100, null=True)),
                ('EstabDay', models.CharField(blank=True, max_length=8, null=True)),
                ('SDAY', models.CharField(blank=True, max_length=8, null=True)),
                ('EDAY', models.CharField(blank=True, max_length=8, null=True)),
                ('CmpCode', models.CharField(blank=True, max_length=10, null=True)),
                ('InvestRegion', models.CharField(blank=True, max_length=10, null=True)),
                ('FundTypeName', models.CharField(blank=True, max_length=20, null=True)),
                ('SalesCode', models.CharField(blank=True, max_length=3, null=True)),
                ('SalesNM', models.CharField(blank=True, max_length=100, null=True)),
                ('MgrName', models.TextField(blank=True, null=True)),
                ('MgrInfo', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tradeday', models.CharField(blank=True, max_length=8, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=12, max_digits=22, null=True)),
                ('Upndown', models.DecimalField(blank=True, decimal_places=12, max_digits=22, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incaDB.Fund')),
            ],
        ),
    ]
