# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incaDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FundCode', models.CharField(blank=True, max_length=20, null=True)),
                ('InsuType', models.CharField(blank=True, max_length=2, null=True)),
                ('ProdCode', models.CharField(blank=True, max_length=20, null=True)),
                ('SalesCode', models.CharField(blank=True, max_length=3, null=True)),
                ('ProdName', models.CharField(blank=True, max_length=150, null=True)),
                ('ProdFlag', models.CharField(blank=True, max_length=50, null=True)),
                ('ProdType', models.CharField(blank=True, max_length=50, null=True)),
                ('SaleSday', models.CharField(blank=True, max_length=8, null=True)),
                ('SaleEday', models.CharField(blank=True, max_length=8, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('funds', models.ManyToManyField(to='incaDB.Fund')),
            ],
        ),
    ]
